const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let bearer='',company='',offset=0,pending=null,busy=false,session=0;
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');
async function request(input){const url=new URL('./control_api.php',location.href);if(company)url.searchParams.set('company',company);url.searchParams.set('offset',offset);const r=await fetch(url,{method:input?'POST':'GET',headers:{Authorization:`Bearer ${bearer}`,'Content-Type':'application/json'},body:input?JSON.stringify(input):undefined,cache:'no-store'});const data=await r.json();if(!r.ok||!data.success)throw Error(data.message||'Permintaan gagal');return data;}
async function refresh(){const current=session,data=await request();if(current!==session)return;let html='';for(const [key,title] of [['companies','Perusahaan'],['properties','Properti'],['principals','Pengguna'],['audit','Audit perubahan']])if(data[key]){html+=`<h3>${title}</h3><div class="table-wrap"><table>`;for(const row of data[key])html+='<tr>'+Object.values(row).map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>';html+='</table></div>';}$('registry').innerHTML=html;$('previous').disabled=offset===0;$('next').disabled=!['companies','properties','principals','audit'].some(k=>data[k]?.length===50);$('page').textContent=`Halaman ${offset/50+1}`;}
$('login-form').onsubmit=async e=>{e.preventDefault();bearer=$('token').value.trim();company=$('company').value.trim();session++;offset=0;try{await refresh();$('token').value='';$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('target-company').value=company;}catch(error){bearer='';$('message').textContent=error.message;}};
$('logout').onclick=()=>{session++;bearer='';pending=null;$('registry').replaceChildren();$('new-token').textContent='';$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;};
for(const [id,direction] of [['previous',-1],['next',1]])$(id).onclick=async()=>{offset=Math.max(0,offset+direction*50);try{await refresh();}catch(e){$('message').textContent=e.message;}};
function fields(){pending=null;const cmd=$('command').value;let html='';if(cmd==='company-create')html='<label>Nama perusahaan<input id="name" required maxlength="190"></label>';if(cmd.startsWith('property-'))html+='<label>Property ID<input id="propertyId" required></label>';if(cmd==='property-register')html+='<label>Secret pengiriman snapshot (samakan dengan konfigurasi private hotel)<input id="secret" type="password" required minlength="32" autocomplete="off"></label>';if(cmd.endsWith('-status'))html+='<label>Status<select id="enabled"><option value="true">Aktif</option><option value="false">Nonaktif</option></select></label>';if(cmd.startsWith('principal-'))html+='<label>User ID<input id="principalId" required></label>';if(cmd==='principal-grant')html+='<label>Peran<select id="role"><option value="viewer">Pembaca laporan</option><option value="finance">Keuangan</option><option value="property_manager">Manajer properti</option><option value="company_admin">Administrator perusahaan</option></select></label><label>Property ID, dipisahkan koma (boleh kosong untuk admin perusahaan)<input id="propertyIds"></label>';$('fields').innerHTML=html;}
$('command').onchange=fields;fields();
$('command-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const input={command:$('command').value,companyId:$('target-company').value.trim()};for(const id of ['name','propertyId','secret','principalId','role'])if($(id))input[id]=$(id).value.trim();if($('enabled'))input.enabled=$('enabled').value==='true';if($('propertyIds'))input.propertyIds=$('propertyIds').value.split(',').map(v=>v.trim()).filter(Boolean);const fingerprint=JSON.stringify(input);if(pending?.fingerprint!==fingerprint)pending={fingerprint,input:{...input,operationId:crypto.randomUUID(),...(input.command==='principal-grant'?{token:random()}:{})}};busy=true;const current=session;try{const result=await request(pending.input);if(current!==session)return;$('message').textContent=`Tersimpan: ${result.operation_id}`;$('new-token').textContent=pending.input.token?`Simpan token pengguna ini: ${pending.input.token}`:'';pending=null;if($('secret'))$('secret').value='';await refresh();}catch(error){if(current===session)$('message').textContent=error.message;}finally{busy=false;}};
