<?php
declare(strict_types=1);require_once dirname(__DIR__).'/release_contract.php';$passed=0;$test=function(string $n,callable $f)use(&$passed){$f();$passed++;echo "PASS $n\n";};$expect=function(bool $x,string $m='assertion failed'){if(!$x)throw new RuntimeException($m);};$root=dirname(__DIR__);$parent=sys_get_temp_dir().DIRECTORY_SEPARATOR.'tamasya-prd-provision-'.bin2hex(random_bytes(6));$target=$parent.'/bundle';mkdir($parent,0700,true);$cleanup=function(string $path)use(&$cleanup){if(!file_exists($path)&&!is_link($path))return;if(is_dir($path)&&!is_link($path)){foreach(scandir($path)?:[] as $n){if($n==='.'||$n==='..')continue;$cleanup($path.'/'.$n);}@rmdir($path);}else @unlink($path);};register_shutdown_function(fn()=>$cleanup($parent));
$input=json_encode(['companyId'=>'prd-company','propertyId'=>'prd-property','url'=>'https://prd-property.example.invalid','databaseHost'=>'db.internal','databasePort'=>3306,'databaseUserHost'=>'10.%'],JSON_THROW_ON_ERROR);$proc=proc_open([PHP_BINARY,$root.'/deploy/provision_property.php',$target],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root);if(!is_resource($proc))throw new RuntimeException('cannot execute provisioner');fwrite($pipes[0],$input);fclose($pipes[0]);$out=stream_get_contents($pipes[1]);fclose($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[2]);$code=proc_close($proc);if($code!==0)throw new RuntimeException(trim($err));$result=json_decode($out,true,32,JSON_THROW_ON_ERROR);
$test('provisioner creates reviewable bundle including migration-authority attestation',function()use($expect,$result,$target){$expect(($result['success']??false)===true);foreach(['provision.sql','release_attestation.sql','runtime.env','db_credentials.php','README.txt'] as $f){$expect(in_array($f,(array)$result['files'],true));$expect(is_file($target.'/'.$f));}});
$att=file_get_contents($target.'/release_attestation.sql');$readme=file_get_contents($target.'/README.txt');$runtime=file_get_contents($target.'/runtime.env');$prov=file_get_contents($target.'/provision.sql');$checksum=tamasyaCanonicalDatabaseSourceChecksum();
$test('attestation pins exact canonical source checksum and release contract',function()use($expect,$att,$checksum){$expect(str_contains($att,"`source_checksum`='$checksum'"));$expect(str_contains($att,"`current_release`='".TAMASYA_SCHEMA_RELEASE."'"));$expect(str_contains($att,"`patch_level`='".TAMASYA_PATCH_LEVEL."'"));});
$test('attestation is explicitly post-verification DBA work, never runtime self-attestation',function()use($expect,$readme,$att){$expect(str_contains($att,'ONLY AFTER database_setup.sql imported successfully'));$expect(str_contains($readme,'BEFORE applying release_attestation.sql'));$expect(str_contains($readme,'exact canonical schema and all trigger signatures'));$expect(str_contains($readme,'Do not mount DBA/migration credentials'));});
$test('generated runtime identity has complete mandatory property startup contract',function()use($expect,$runtime){foreach(['APP_TIMEZONE=Asia/Makassar','TAMASYA_PROPERTY_ID=prd-property','TAMASYA_PROPERTY_CODE=PRDPROPERTY','TAMASYA_PROPERTY_NAME=prd-property','TAMASYA_PROPERTY_CURRENCY=IDR','TAMASYA_PROPERTY_COUNTRY=ID','TAMASYA_PROPERTY_LOCALE=id-ID'] as $m)$expect(str_contains($runtime,$m),$m);});
$test('generated database runtime grant remains data-plane only',function()use($expect,$prov){$expect(str_contains($prov,'GRANT SELECT,INSERT,UPDATE,DELETE'));foreach(['GRANT ALL',' TRIGGER ',' SUPER ',' ALTER ',' DROP '] as $f)$expect(!str_contains(strtoupper($prov),strtoupper($f)),$f);});$cleanup($parent);echo "$passed passed; 0 failed\n";
