(function () {
  "use strict";

  // Generated by scripts/apply-production-config.mjs. URLs only; never store secrets here.
  const runtime = Object.freeze({
    API_URL: "https://app.nolink.my.id/api.php",
    SITE_URL: "https://tamasya.nolink.my.id"
  });

  window.TAMASYA_PUBLIC_RUNTIME = runtime;
  window.TAMASYA_PUBLIC_API_URL = runtime.API_URL;
  window.TAMASYA_PUBLIC_SITE_URL = runtime.SITE_URL;
})();
