[www]
listen=9000
pm=dynamic
pm.max_children=8
pm.start_servers=2
pm.min_spare_servers=2
pm.max_spare_servers=4
pm.max_requests=500
clear_env=no
catch_workers_output=yes
request_terminate_timeout=65s
request_slowlog_timeout=3s
slowlog=/proc/self/fd/2
